# Generated by Django 4.1.7 on 2023-03-11 14:58

import computedfields.resolver
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=50, unique=True)),
                ('rent_due', models.FloatField()),
                ('rent_paid', models.FloatField(default=0)),
                ('starting_date', models.DateField()),
                ('due_date', models.DateField()),
                ('deposit', models.FloatField(default=0)),
                ('location', models.CharField(max_length=100)),
                ('balance', models.FloatField(editable=False)),
                ('remainig_days', models.IntegerField(editable=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
    ]
